### ISSUE TITLE
Question about requirement

### ISSUE THREAD

**Issue by waghanza** [foxifyjs/foxify#4]
Hi @ardalanamini,

`Foxify` require `node >= 8.12`.

Is there any feature required by `foxify` not in `node 8.11` ?

Regards,

**Comment by ardalanamini** [comment]
@waghanza Hi
Yes, `Foxify` uses `http.createServer()`'s options to create request and response objects according to it's own classes, so it won't need to add prototypes to these objects after they are created.
The ability is added to `Node.js` since `v8.12.0` ([See the Changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#2018-09-11-version-8120-carbon-lts-mylesborins))
