### ISSUE TITLE
support nest.js & apllo-graphql & typeorm 

### ISSUE THREAD

**Issue by zuohuadong** [foxifyjs/foxify#5]
**Is your feature request related to a problem? Please describe.**

use nest.js  apllo-graphql & typeorm

**Comment by ardalanamini** [comment]
@zuohuadong would you describe your feature request more?

**Comment by zuohuadong** [comment]
1. https://www.apollographql.com/   apollo server support  express  koa  ... 

2. how to use  https://typeorm.io/  in foxify .

3. https://github.com/nestjs/nest 
The underlying nest.js can use express or fastify, how to use foxify?

**Comment by ardalanamini** [comment]
@zuohuadong 
1. you can use almost any `express` middleware in `foxify`, so if `express` supports it, then `foxify` supports it too. so `apollographql` is already supported.

2. you can use `typeorm` in `foxify` just like using it in `express`, since `typeorm` is an database model that doesn't depend on any framework.

3. `nestjs` has to include `foxify` support just like `fastify` in its core. as you can see in [here](https://docs.nestjs.com/techniques/performance), `FastifyAdapter` is part of `@nestjs/core`.

**Comment by zuohuadong** [comment]
> @zuohuadong
> 
> 1. you can use almost any `express` middleware in `foxify`, so if `express` supports it, then `foxify` supports it too. so `apollographql` is already supported.
> 2. you can use `typeorm` in `foxify` just like using it in `express`, since `typeorm` is an database model that doesn't depend on any framework.
> 3. `nestjs` has to include `foxify` support just like `fastify` in its core. as you can see in [here](https://docs.nestjs.com/techniques/performance), `FastifyAdapter` is part of `@nestjs/core`.

Thanks for the reply. 

I hope to have such an upper package：
https://github.com/nestjs/graphql
https://github.com/nestjs/typeorm
